### ISSUE TITLE
Extra intermediate sources in resulting sourcemap

### ISSUE THREAD

**Issue by wilsonjackson** [Kagami/gulp-ng-annotate#25]
When I add `gulp-ng-annotate` to my gulp build after `gulp-typescript`, the resulting map includes filenames with both `.ts` and `.js` extensions, effectively duplicating every source file. E.g., 

```
{"version":3,"sources":["app.ts","app.js","module1/module1.ts","module1/module1.js"...
```

Without `gulp-ng-annotate`, it contains only `.ts` extensions, as it should.

I've created a sample repo here: https://github.com/wilsonjackson/typescript-ng-annotate

Clone that, run `npm install` and `gulp`, and check out `dist/bundle.js.map`.

**Comment by Kagami** [comment]
Well, I can say this is not related to `gulp-ng-annotate`'s [workaround](https://github.com/Kagami/gulp-ng-annotate/issues/9#issuecomment-65946516) for a sourcemap `file` property. Without that workaround, `gulp-sourcemaps` can't merge source maps produced by `typescript` at all. So [this bug](https://github.com/ivogabe/gulp-typescript/issues/44) is not `gulp-ng-annotate`'s bug strictly speaking, it should have been reported to `typescript` or to `gulp-sourcemaps` or `vinyl-sourcemaps-apply` or `source-map`. I've just added it to `gulp-ng-annotate` because it was easy to do. But probably it can bring more harm than benefits in a long run...

Regarding duplicated files: it's a [known problem](https://github.com/Kagami/gulp-ng-annotate/issues/9#issuecomment-65958600) and I think the best answer on this problem was given by  @smrq [here](https://github.com/Kagami/gulp-ng-annotate/issues/9#issuecomment-65504242).

I'm not an expert in sourcemaps, so any help on this would be greatly appreciated. @smrq was mentioned [possible workaround](https://github.com/smrq/remove-source-mapping), but I believe this should be done by `source-map` library instead, I don't think every plugin that combines sourcemaps should apply hacks to this process. So I think this problem should be generalized and reported to upstream. If you disagree with me - suggestions are welcomed.

Also I'm going to close #9 because it became too messy. Seems like the only problem regarding sourcemaps still exists, is the extra intermediate sources.

**Comment by yanhkim** [comment]
I had same issues on my project, too. My case's similar: sourcemap(typescript + ngAnnotate)

I decided ngAnnotate not to generate sourcemap by adding `{ map: false }` option. I guess ng-annotate does not add or remove extra lines during its transform. So it seems fine..
